### ISSUE TITLE
게시글 작성 시간이 잘못 나옵니다

### ISSUE THREAD

**Issue by Laterality** [woowa-turkey/miniprojects-2019#106]
게시글 작성시 방금 전으로 출력돼야 하는 게시글 작성 시간이 잘못(22시간 전) 표시되고 있습니다.

**Comment by pkch93** [comment]
db 시간 문제

**Comment by yk1028** [comment]
리눅스를 새로 설치하고 나면 (AWS EC2 AMI도 Linux와 동일) 시간대(Timezone)을 맞추지 않으면, 리눅스의 date가 미국 태평양 시간인 PST로 표시됩니다. 즉 캘리포니아 현지 시간으로 표시됩니다. 이럴경우 한국 표준시인 KST로 변경해주어야 합니다.

```
$ sudo rm /etc/localtime // 기존 시간대 삭제
$ sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime // Seoul로 시간대 변경
```

출처: https://ora-sysdba.tistory.com/entry/Cloud-Computing-Amazon-EC2-인스턴스의-TIMEZONE-변경 [Welcome To Ora-SYSDBA]
