### ISSUE TITLE
[bug] 친구 삭제시 의도하지 않은 에러메시지

### ISSUE THREAD

**Issue by kangmin46** [woowa-turkey/miniprojects-2019#115]
기대하는 효과 : 올바른 친구 삭제 메시지

실제 효과 : 
![image](https://user-images.githubusercontent.com/40996389/64003700-c46b6580-cb47-11e9-8637-6baa7d7b404a.png)

**Comment by yk1028** [comment]
icon 누를시 에러가 발생
