### ISSUE TITLE
img가 카드 크기보다 클때 깨지는 현상

### ISSUE THREAD

**Issue by pkch93** [woowa-turkey/miniprojects-2019#75]

**Comment by school0bhy** [comment]
image가 카드 크기보다 클때 깨지는 현상 없어서 닫습니다..ㅎㅎㅎ

(아까 데모때 문제는 게시글 글자 입력란에 img 태그 이용해서 사진 나오게 할때의 문제임 - 이거는 사이즈 설정 안되어 있으니까)

**Comment by school0bhy** [comment]
댓글 입력 후 보여줄 때도 마찬가지
+ 검색도..
